version: 2
updates:
  - package-ecosystem: pip
    directory: /project-2
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
